language: "python"
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - "python setup.py develop"
before_script:
  - pip install -r requirements.txt
script: "coverage run --source=jolokia setup.py test"
after_success:
  - coveralls