language: "python"
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - "python setup.py develop"
  - "pip install -r requirements.txt"
script: "py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing"
after_success:
  - coveralls