language: python
python:
- 2.7
- 3.4
- 3.5
install:
- python setup.py develop
before_script:
- pip install pipenv
- pipenv install --dev
script:
- pytest --cov=jolokia tests/
- pylint jolokia
after_success:
- coveralls
notifications:
  email: false
jobs:
  include:
  - stage: PyPI and GitHub release
    python: 3.6
    deploy:
    - provider: releases
      api_key:
        secure: dGRgtqtV/dZrWCguslh2sqY6ec83kKzUIofUQhe+ikuW9TojWStkxryGdelhLCjJ8Z9NRduLBuOWIBtm76vVuxmKsF3g0Flk8bZLFKtFy6kuPrQErVrTlUuNjoEj6epcyUb8GhYEYcTnCNReeLizlOVzpuQHqRpP5zm4R0O04TzaDPMDpAGJkba4oajx/s/kIz7+qc5veL4Z4XqXMSuAsiGnZyGcTkG+HlUJ045+iLzpZh4qO3gZojeqLgOLetS4tE8UV6fls0D6+kUsz1YHUbz1NV/IZOs4ad2UBzSrC5/zvfQWDk8Fdzl76OoogpQA3mi3q1ustLbuZ5frNLA39X/dT/vpMk5UizWJ+iDZp5NFlz5LR+j0Ssx/N1XUuONRmNg5/3SoUdoDeVtAwAQToOGwbI1f+ZRoeUj+FE5iEiu776NUVRE+T2jvWGzq4tH/pADIqFLwRuT1NPazENTolL3H54qTPr7JmTomhTOlKDRBKtr2nVx9hpuAfkBEk4y71/+2GYxgEqQa1hNmnOalNyjvTGh6sVbWJ8YdncADhEYa8tS5gQkFwEjco41zywuQlUcFvXBQw83dOOXfJuzBd9njrI01eNfSQn8zrQk8PJnbcrljLIYWQvnIgeZV+0vLbgBCFnAwHYyYEmHj1anMZMSFaG9i8Mvj/6DPVzqGOP8=
      on:
        tags: true
      branch: master
      name: ${TRAVIS_TAG}
      draft: true
    - provider: pypi
      username: wbrefvem
      password:
          secure: kgXNyuu0a212wfSIWsxYSLPBeU/ZEU4B2Gi1PgBobVc5FpfV2iKh5ScB72xebnanCMTdjhYQKfEpv8QVwyBCQDKghqC2zGi4lgQuJsK37fbo6e9gyJoWTTMlMrx70iDB6kd89MEQwWcygyLBELwe3Zu5LpQoXxXgfcdj1ES5rU6nBE5TYc2zOEiwY4Kh04/w9Zp9MH4arcBN7VXCOWcHEtxnI0iiCZ6Vp6aEgRD9QTg0zgdEOo1WEH6Sxx++xDBiy6sKXijOCY0z/zPR3u7TOCWBoetPRmB8LQlII3UvALY3aGDDftx/uISc9vYExpNOS5qg8vZgN/SF6HFPVua2MaU1+JJYu3OcunPl9Jgy6hPyvn+FA4H2Xnel5ltqBit2tamGpSuYL6SBI0bwBKU0GnVgpsCGbDoD7ODnjQLXO0gVrQXBRXkSS1ArCWcr1KCGb7VXXoYX3/e5/1ul75xDnPLRzP8FZtHEPOciowowS57NAJHreGMStnjJppDd+NjaoFHXh+Jw2PsyLMVlddqRvxp20T1GuFKsZwNeEQIfgT9YzhZo1vj7KaGUfk90zj2t9Znb23HwkjTqlC7K4g9DVLGyunqrcxX7H9tCQPPRaB3WkNviK2ZsYM2ms7+TNlczMhRyVdUrgDLUgj8xCzf+bYhKbj3FPJpqa9LK8zug5KA=
      on:
        tags: true
      distributions: "sdist bdist_wheel"
